baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Progress Group'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 2



[params]
  description = "Компания по производству вагон-домов"