backend:
  name: git-gateway
  branch: main # Или master, в зависимости от имени вашей основной ветки
media_folder: 'static/images' # Папка для загрузки медиафайлов
public_folder: '/images' # Публичный путь к медиафайлам на сайте

collections:
  - name: 'news'
    label: 'Новости'
    folder: 'content/news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Дата публикации', name: 'date', widget: 'datetime' }
      - { label: 'Автор', name: 'author', widget: 'string' }
      - { label: 'Текст новости', name: 'body', widget: 'markdown' }

  - name: 'products'
    label: 'Товары'
    folder: 'content/products'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Цена', name: 'price', widget: 'string' }
      - { label: 'Изображение', name: 'image', widget: 'image' }
      - { label: 'Краткое описание', name: 'description', widget: 'markdown' }
      - { label: 'Текст', name: 'body', widget: 'markdown' }
      - {
          label: 'Категории',
          name: 'categories',
          widget: 'list',
          field: { label: 'Категория', name: 'category', widget: 'string' },
        }

  - name: 'pages'
    label: 'Страницы'
    files:
      - file: 'content/_index.md'
        label: 'Главная страница'
        name: 'home'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'content/about.md'
        label: 'О компании'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'content/contacts.md'
        label: 'Контакты'
        name: 'contacts'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
