backend:
  name: git-gateway
  branch: main # или master

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'blog'
    label: 'Блог'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Дата', name: 'date', widget: 'datetime' }
      - { label: 'Текст', name: 'body', widget: 'markdown' }
